### ISSUE TITLE
Applying a License or a Public Domain statement for this repository

### ISSUE THREAD

**Issue by Tensa53** [NJUJisq/DS_Python#1]
Hello everyone, my name is Daniele Fabiano and i am a CS Student from University of Salerno. In the last 6 months i am working on the thesis for my bachelor degree. This thesis covers some topics about the detection of Bloated Dependencies and their related vulnerabilities. I decided to fork your project because for the tool i've been building, i need a comfortable file format (such as .csv) to retrieve information about the dependencies of an analyzed project. So inside my tool i am using your GetDep_ast.py script. However, the original repo does not have any license or information about an eventually public domain source code. If you don't fix this, i can encounter some issues about copyright. So what i want to ask you, could you please add a license on the repository or release the public domain statement for your source code?
Thank you so much.
Best regards,
Daniele

**Comment by NJUJisq** [comment]
Hi, I have added the  MIT license.

**Comment by Tensa53** [comment]
Hi, thank you for applying the license
